"use client";

import { useState } from "react";
import { SectionTitle, Pill, TextInput, Button } from "../../components/ui";
import { useAppContext } from "../AppContext";

interface NewReview {
  assetTitle: string;
  reviewType: string;
  comment: string;
  due: string;
}

export default function ReviewsPage() {
  const appContext = useAppContext();
  const [showForm, setShowForm] = useState(false);
  const [formData, setFormData] = useState<NewReview>({
    assetTitle: "",
    reviewType: "LEGAL REVIEW",
    comment: "",
    due: "TODAY",
  });
  const [reviewStatuses, setReviewStatuses] = useState<Record<string, string>>({});

  // Generiere Reviews aus Critical und High-Risk Claims
  const autoGeneratedReviews = [
    ...appContext.getCriticalClaims().map((claim, i) => ({
      id: `auto_c_${i}`,
      claimId: claim.id,
      assetTitle: claim.text.substring(0, 40) + (claim.text.length > 40 ? "..." : ""),
      reviewType: "LEGAL REVIEW",
      comment: claim.explanation,
      due: "TODAY",
      status: reviewStatuses[`auto_c_${i}`] || "PENDING",
      source: claim.sourceUrl || "Manuelle Eingabe",
    })),
    ...appContext.getHighRiskClaims().map((claim, i) => ({
      id: `auto_h_${i}`,
      claimId: claim.id,
      assetTitle: claim.text.substring(0, 40) + (claim.text.length > 40 ? "..." : ""),
      reviewType: "ESG REVIEW",
      comment: claim.explanation,
      due: "TOMORROW",
      status: reviewStatuses[`auto_h_${i}`] || "PENDING",
      source: claim.sourceUrl || "Manuelle Eingabe",
    })),
  ];

  const handleStatusChange = (id: string, newStatus: string) => {
    setReviewStatuses({ ...reviewStatuses, [id]: newStatus });
  };

  const getStatusColor = (status: string) => {
    const colors: Record<string, string> = {
      PENDING: "var(--color-risk-medium)",
      APPROVED: "var(--color-risk-low)",
      CHANGES_REQUESTED: "var(--color-risk-high)",
      REJECTED: "var(--color-risk-critical)",
    };
    return colors[status] || "var(--text-secondary)";
  };

  const pendingCount = autoGeneratedReviews.filter(r => r.status === "PENDING").length;
  const changesCount = autoGeneratedReviews.filter(r => r.status === "CHANGES_REQUESTED").length;
  const approvedCount = autoGeneratedReviews.filter(r => r.status === "APPROVED").length;

  if (autoGeneratedReviews.length === 0) {
    return (
      <main>
        <section style={{ padding: "40px 0" }}>
          <SectionTitle eyebrow="Freigaben" title="Review- & Freigabe-Queue" />
          <div className="panel" style={{ textAlign: "center", padding: "40px", color: "var(--text-muted)" }}>
            <p>Noch keine Reviews ausstehend. Analysieren Sie Texte oder URLs, um automatisches Review-Feedback zu erhalten.</p>
          </div>
        </section>
      </main>
    );
  }

  return (
    <main>
      <section style={{ padding: "40px 0" }}>
        <SectionTitle eyebrow="Freigaben" title="Review- & Freigabe-Queue" />

        {/* Summary */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16, marginBottom: 28 }}>
          <div className="panel">
            <div style={{ fontSize: "24px", fontWeight: 600, color: "var(--color-accent)", marginBottom: 4 }}>
              {autoGeneratedReviews.length}
            </div>
            <div style={{ fontSize: "11px", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--text-muted)" }}>
              Gesamt Reviews
            </div>
          </div>
          <div className="panel">
            <div style={{ fontSize: "24px", fontWeight: 600, color: "var(--color-risk-medium)", marginBottom: 4 }}>
              {pendingCount}
            </div>
            <div style={{ fontSize: "11px", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--text-muted)" }}>
              Ausstehend
            </div>
          </div>
          <div className="panel">
            <div style={{ fontSize: "24px", fontWeight: 600, color: "var(--color-risk-high)", marginBottom: 4 }}>
              {changesCount}
            </div>
            <div style={{ fontSize: "11px", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--text-muted)" }}>
              Änderungen gewünscht
            </div>
          </div>
          <div className="panel">
            <div style={{ fontSize: "24px", fontWeight: 600, color: "var(--color-risk-low)", marginBottom: 4 }}>
              {approvedCount}
            </div>
            <div style={{ fontSize: "11px", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--text-muted)" }}>
              Genehmigt
            </div>
          </div>
        </div>



        {/* Reviews List */}
        <div className="panel">
          {autoGeneratedReviews.map((r, i) => (
            <div className="row" key={r.id} style={{ borderTop: i === 0 ? "none" : "1px solid var(--border-subtle)" }}>
              <div style={{ flex: 1 }}>
                <div className="row-title">{r.assetTitle}</div>
                <div className="row-meta">
                  {r.reviewType} · Quelle: {r.source}
                </div>
                <div className="muted" style={{ marginTop: 8 }}>{r.comment}</div>
              </div>
              <div style={{ display: "flex", gap: 12, alignItems: "center", minWidth: "200px" }}>
                <select
                  value={r.status}
                  onChange={(e) => handleStatusChange(r.id, e.target.value)}
                  style={{
                    padding: "8px 12px",
                    borderRadius: "var(--radius-sm)",
                    border: `1px solid ${getStatusColor(r.status)}`,
                    backgroundColor: "transparent",
                    color: getStatusColor(r.status),
                    fontSize: "12px",
                    cursor: "pointer",
                    fontWeight: 500,
                  }}
                >
                  <option value="PENDING">Ausstehend</option>
                  <option value="APPROVED">Genehmigt</option>
                  <option value="CHANGES_REQUESTED">Änderungen gewünscht</option>
                  <option value="REJECTED">Abgelehnt</option>
                </select>
              </div>
            </div>
          ))}
        </div>
      </section>
    </main>
  );
}
